# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: quay.io/cilium/cilium:v1.16.12
    newName: localhost:5000/cilium/cilium-dev
    newTag: local
  - name: quay.io/cilium/operator-generic:v1.16.12
    newName: localhost:5000/cilium/operator-generic
    newTag: local

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cilium-operator
      namespace: kube-system
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --minimum-lbip-pools-required=2
