apiVersion: v1
kind: Namespace
metadata:
  name: tenant-blue

---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-red

---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      bgp: "65001"
  bgpInstances:
  - name: "65002"
    localASN: 65002
    peers:
    - name: "65001"
      peerASN: 65001
      peerAddress: 127.0.0.1
      peerConfigRef:
        name: "cilium-peer"

---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
spec:
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "bgp"

---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisements
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: "PodCIDR"
      attributes:
        communities:
          standard: [ "65000:99" ]
    - advertisementType: "Service"
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchExpressions:
         - {key: somekey, operator: NotIn, values: ['never-used-value']}
      attributes:
        communities:
          standard: [ "65000:300" ]
    - advertisementType: "Service"
      service:
        addresses:
          - ClusterIP
          - ExternalIP
      selector:
        matchExpressions:
          - { key: bgp, operator: In, values: [ blue ] }
      attributes:
        communities:
          standard: [ "65000:100" ]
    - advertisementType: "Service"
      service:
        addresses:
          - ClusterIP
          - ExternalIP
      selector:
        matchExpressions:
          - { key: bgp, operator: In, values: [ red ] }
      attributes:
        communities:
          standard: [ "65000:200" ]
# ---
# apiVersion: cilium.io/v2alpha1
# kind: CiliumBGPNodeConfigOverride
# metadata:
#   name: bgpv2-cplane-dev-service-control-plane
# spec:
#   bgpInstances:
#     - name: "65002"
#       routerID: 127.0.0.1
#
# ---
# apiVersion: cilium.io/v2alpha1
# kind: CiliumBGPNodeConfigOverride
# metadata:
#   name: bgpv2-cplane-dev-service-worker
# spec:
#   bgpInstances:
#     - name: "65002"
#       routerID: 127.0.0.1
