# ---
# apiVersion: "cilium.io/v2alpha1"
# kind: CiliumLoadBalancerIPPool
# metadata:
#   name: "ip-pool-blue"
#   labels:
#     bgp: blue
# spec:
#   blocks:
#     - cidr: "20.0.10.0/24"
#   serviceSelector:
#     matchExpressions:
#       - {key: bgp, operator: In, values: [blue]}

---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "ip-pool-red"
  labels:
    bgp: red
spec:
  allowFirstLastIPs: "No"
  blocks:
    - cidr: "20.1.10.2/32"
  serviceSelector:
    matchExpressions:
      - {key: bgp, operator: In, values: [red]}

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: lb-service-blue
#   namespace: tenant-blue
#   labels:
#     bgp: blue
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 1234
#   externalTrafficPolicy: Local
#   selector:
#     app: curl-blue

---
apiVersion: v1
kind: Service
metadata:
  name: lb-service-red
  namespace: tenant-red
  labels:
    bgp: red
spec:
  type: LoadBalancer
  ports:
    - port: 1236
