apiVersion: v1
kind: Namespace
metadata:
  name: bastion

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-echo
  namespace: bastion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-echo
  template:
    metadata:
      labels:
        app: ubuntu-echo
    spec:
      nodeSelector:
        kubernetes.io/hostname: bgp-migration-control-plane
      containers:
        - name: ubuntu
          image: hashicorp/http-echo
          args:
            - "-text=Hello from Ubuntu echo server!"
            - "-listen=:8080"
          ports:
            - containerPort: 8080 
---
apiVersion: v1
kind: Service
metadata:
  name: bastion
  namespace: bastion
  annotations:
    metallb.universe.tf/address-pool: bastion
  labels:
    metallb.universe.tf/address-pool: bastion
spec:
  type: LoadBalancer
  selector:
    app: ubuntu-echo
  ports:
    - port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-echo
  template:
    metadata:
      labels:
        app: ubuntu-echo
    spec:
      nodeSelector:
        kubernetes.io/hostname: bgp-migration-control-plane
      containers:
        - name: ubuntu
          image: hashicorp/http-echo
          args:
            - "-text=Hello from Ubuntu echo server!"
            - "-listen=:8080"
          ports:
            - containerPort: 8080 
---
apiVersion: v1
kind: Service
metadata:
  name: default-lb
spec:
  type: LoadBalancer
  selector:
    app: ubuntu-echo
  ports:
    - port: 80
      targetPort: 8080
