apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: default
  labels:
    app: ubuntu
spec:
  nodeSelector:
    kubernetes.io/hostname: bgp-migration-control-plane
  containers:
    - name: curl
      image: curlimages/curl
      command: ["sleep", "infinit"]
---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-worker
  namespace: default
  labels:
    app: ubuntu
spec:
  nodeSelector:
    kubernetes.io/hostname: bgp-migration-worker
  containers:
    - name: curl
      image: curlimages/curl
      command: ["sleep", "infinit"]

