bgp:
  announce:
    loadbalancerIP: true
  enabled: true
bpf:
  hostLegacyRouting: true
  policyMapMax: 65536
  mapDynamicSizeRatio: 0.005
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
cni:
  chainingMode: "generic-veth"
  customConf: true
conntrackGCMaxInterval: 30m
datapathMode: "veth"
devices: "eth+ eno1+ eno2+"
enableIPv4Masquerade: false
enableIdentityMark: false
externalIPs:
  enabled: true
extraArgs:
  - "--endpoint-gc-interval=0"
  - "--bpf-ct-timeout-regular-tcp=2h13m20s"
  - "--bpf-ct-timeout-service-tcp=2h13m20s"
  - "--label-prefix-file=/etc/label-prefix/label-prefix.json"
extraConfig:
  bpf-ct-timeout-regular-any: 1h0m0s
  bpf-ct-timeout-service-any: 1h0m0s
extraVolumes:
  - name: label-prefix
    configMap:
      name: cilium-label-prefix
extraVolumeMounts:
  - name: label-prefix
    mountPath: /etc/label-prefix
hostPort:
  enabled: false
hubble:
  metrics:
    enableOpenMetrics: true
    enabled:
      - "drop:sourceContext=reserved-identity;destinationContext=reserved-identity;labelsContext=source_namespace,destination_namespace,traffic_direction"
      - "icmp:sourceContext=reserved-identity;destinationContext=reserved-identity;labelsContext=source_namespace,destination_namespace"
      - "tcp:sourceContext=reserved-identity;destinationContext=reserved-identity;labelsContext=source_namespace,destination_namespace"
    port: 9965
  relay:
    enabled: true
    tls:
      server:
        enabled: true
    rollOutPods: true
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
    podLabels:
      identity.neco.cybozu.io/name: hubble-relay
    podSecurityContext:
      fsGroup: 10000
    securityContext:
      runAsUser: 10000
      runAsGroup: 10000
  tls:
    auto:
      method: "cronJob"
k8sServiceHost: 127.0.0.1
k8sServicePort: 16443
# kubeProxyReplacement: "partial"
kubeProxyReplacement: true
labels: "
  k8s:app
  k8s:io\\.cilium\\.k8s\\.namespace\\.labels
  k8s:io\\.kubernetes\\.pod\\.namespace
  k8s:k8s-app 
  io\\.cilium\\.k8s\\.policy
  cybozu\\.io/family
  app\\.cybozu\\.io
  neco\\.cybozu\\.io\\/registry
  identity\\.neco\\.cybozu\\.io
  "
loadBalancer:
  # We can't enable XDP Acceleration because rolling restart Cilium with XDP enabled disrupts in-cluster connectivity
  acceleration: disabled
  algorithm: maglev
  dsrDispatch: geneve
  dsrL4Translate: backend
  mode: dsr
maglev:
  hashSeed: 3HCx6JennjWtot2U
nodePort:
  directRoutingDevice: "e+"
  enabled: true
operator:
  rollOutPods: true
  prometheus:
    enabled: true
  resources:
    requests:
      cpu: 30m
      memory: 660Mi
policyAuditMode: false
policyEnforcementMode: "default"
pprof:
  enabled: true
  address: "0.0.0.0"
  port: 6060
prometheus:
  enabled: true
  metrics:
    - +cilium_bpf_map_pressure
resources:
  requests:
    cpu: 1200m
    memory: 10752Mi
rollOutCiliumPods: true
routingMode: "native"
sessionAffinity: true
socketLB:
  enabled: true
  hostNamespaceOnly: true
tunnelProtocol: geneve
updateStrategy:
  rollingUpdate: null
  type: OnDelete
upgradeCompatibility: "1.14"
