apiVersion: apps/v1
kind: Deployment
metadata:
  name: coil-controller
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: coil-controller
        env:
        - name: KUBERNETES_SERVICE_HOST
          value: "127.0.0.1"
        - name: KUBERNETES_SERVICE_PORT
          value: "16443"
