apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: coild
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: coild
        env:
        - name: KUBERNETES_SERVICE_HOST
          value: "127.0.0.1"
        - name: KUBERNETES_SERVICE_PORT
          value: "16443"
