apiVersion: v1
kind: Namespace
metadata:
  name: tenant-green

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-echo
  namespace: tenant-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ubuntu-echo
  template:
    metadata:
      labels:
        app: ubuntu-echo
    spec:
      nodeSelector:
        kubernetes.io/hostname: bgpv2-cplane-dev-service-control-plane
      containers:
        - name: ubuntu
          image: hashicorp/http-echo
          args:
            - "-text=Hello from Ubuntu echo server!"
            - "-listen=:8080"
          ports:
            - containerPort: 8080
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "ip-pool-green"
  labels:
    bgp: green
spec:
  allowFirstLastIPs: "No"
  blocks:
    - cidr: "20.1.10.3/32"
  serviceSelector:
    matchExpressions:
      - {key: bgp, operator: In, values: [green]}

---
apiVersion: v1
kind: Service
metadata:
  name: lb-service-green
  namespace: tenant-green
  labels:
    bgp: green
spec:
  type: LoadBalancer
  selector:
    app: ubuntu-echo
  ports:
    - port: 80
      targetPort: 8080
