---
apiVersion: v1
kind: Service
metadata:
  name: service-blue
  namespace: tenant-blue
  labels:
    bgp: blue
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: curl-blue

---
apiVersion: v1
kind: Service
metadata:
  name: service-red
  namespace: tenant-red
  labels:
    bgp: red
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: curl-red

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-blue
  namespace: tenant-blue
  labels:
    app: curl-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: curl-blue
  template:
    metadata:
      labels:
        app: curl-blue
    spec:
      containers:
        - name: curl
          image: curlimages/curl
          command: ["sleep", "infinit"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-red
  namespace: tenant-red
  labels:
    app: curl-red
spec:
  replicas: 2
  selector:
    matchLabels:
      app: curl-red
  template:
    metadata:
      labels:
        app: curl-red
    spec:
      containers:
        - name: curl
          image: curlimages/curl
          command: ["sleep", "infinit"]
