# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# if you want to force all resources into `default`, uncomment:
# namespace: default

resources:
  - rbac.yaml
  - job.yaml
