apiVersion: v1
kind: ConfigMap
metadata:
  name: bgp-config
  namespace: kube-system
data:
  config.yaml: |
    peers:
    - peer-address: 127.0.0.1
      peer-asn: 65001
      my-asn: 65002
      node-selectors:
      - match-labels:
          bgp: "65001"
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 20.1.30.2/32
