apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: default
spec:
  allowFirstLastIPs: "No"
  blocks:
    - cidr: "20.1.30.2/24"
  # serviceSelector:
  #   matchExpressions:
  #     - {key: metallb.universe.tf/address-pool, operator: In, values: [bastion]}
